# espanso match file
# For a complete introduction, visit the official docs at: https://espanso.org/docs/
# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: "-espanso"
    replace: "Hi there!"

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  # Print the current date
  - trigger: "-date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Print the output of a shell command
  - trigger: "-myshell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"
  # And much more! For more information, visit the docs: https://espanso.org/docs/

  # Email Related Shortcuts
  - trigger: ":gem"
    replace: "williamfernsv3@gmail.com"

  - trigger: "-ys"
    replace: "https://youtube.com/results?search_query="

  - trigger: "-ghs"
    replace: "https://github.com/search?q="

  - trigger: "-gs"
    replace: "https://google.com/search?q="

  - trigger: "-rs"
    replace: "https://replit.com/search?query="

  - trigger: "-rpp"
    replace: "https://replit.com/@WilliamFernsV3"

  - trigger: "-rnb"
    replace: "https://replit.com/bounties?status=open&order=creationDateDescending"

  - trigger: "-ncslofi"
    replace: "https://www.youtube.com/watch?v=KsXttVfPVQM&t=3327s&ab_channel=Stomp%27sPlaylist"
  - trigger: ":greet"
    replace: "Greetings!\nWilliam Ferns"

  - trigger: "-gpp"
    replace: "https://github.com/WilliamFernsV3/"

  - trigger: "-gap"
    replace: "https://github.com/Automa-Automations/"

  - trigger: "-ypp"
    replace: "https://youtube.com/@WilliamFernsV3"

  - trigger: "-ghpr"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "cat ~/.config/espanso/match/outputs/code/github-pr.txt"

  # anchor tag shorthand
  - trigger: "-htmla"
    replace: '<a href="T" target="_blank">B</a>'

  - trigger: "-ghit" # github issue template
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "cat ~/.config/espanso/match/outputs/code/github-issue.txt"

  - trigger: "-twd"
    replace: "https://tailwindcss.com/docs/installation"

  - trigger: "-ghpt" # Github Profile Readme Template for short personal projects
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "cat ~/.config/espanso/match/outputs/code/githubprojecttemplate.txt"


  - trigger: "-mdnd"
    replace: "https://developer.mozilla.org/en-US/docs/Web"

  - trigger: "-calendll"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "cat ~/.config/espanso/match/outputs/contacts/calendll.txt"

  - trigger: "-calendly"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "cat ~/.config/espanso/match/outputs/contacts/calendly.txt"

  - trigger: "-cui"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "cat ~/.config/espanso/match/outputs/code/chakrauijsxtemplate.txt"

  - trigger: "-dsacourse" # data structures and algorithms course
    replace: "https://www.youtube.com/watch?v=RBSGKlAvoiM&ab_channel=freeCodeCamp.org"

  - trigger: "-aafigma" # automa figma design link
    replace: "https://www.figma.com/file/T0V1EjcNGZrqIRSZr4iePz/Automa-Design?type=design&node-id=5%3A2&mode=design&t=AvvwdL4LCa9DZaa4-1"
